In [2]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [3]:
x = np.arange(4, dtype=np.int64)
x_ = np.ones_like(x)
x_

array([1, 1, 1, 1])

Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [4]:
X = np.array([[1, 2], [3, 4]])
X_matrix = np.matrix(X)

Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [6]:
array_evenly_spaced = np.linspace(3.0, 10.0, 50)
array_evenly_spaced

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [7]:
x = np.array([[1, 2, 3], [4, 5, 6]])
a_ = np.ravel(np.transpose(x))
a_


array([1, 4, 2, 5, 3, 6])

Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [9]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])
r_array = np.split(x, [4,6])
r_array

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [12]:
X = np.array([[1, 2], [3, 4]])

X_inv = np.linalg.inv(X)

trace = np.trace(X)

print(trace)
X_inv

5


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [13]:
x = np.array([[1, 4], [3, 1]])

sort_x = np.sort(x, axis=1)
sort_x

array([[1, 4],
       [1, 3]])

Q8 Get the indices that would sort x(as above) along the second axis.

In [14]:
ind_sort = np.argsort(x, axis = 1)
ind_sort

array([[0, 1],
       [1, 0]])

Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [15]:
x = np.random.uniform(0, 10, (2, 5))

max = np.max(x, axis = 1)
min = np.min(x, axis = 1)

max_ind = np.argmax(x, axis = 1)
min_ind = np.argmax(x, axis = 1)

print(max)
print(min)
print(max_ind)
print(min_ind)

[9.52501645 9.07582224]
[3.85862238 0.17207344]
[0 4]
[0 4]


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [16]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Drop rows that contain a missing value.

In [18]:
iris_2d = iris_2d[~np.isnan(iris_2d).any(axis=1)]
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Find the correlation between first two columns.

In [20]:
corr_matrix = np.corrcoef(iris_2d[:, :2], rowvar = False)[0, 1]
corr_matrix

-0.10936924995064935

Find the mean,median and standard deviation of column 3.

In [22]:
c = iris_2d[:, 2]

mean_= np.mean(c)
median_ = np.median(c)
std_= np.std(c)

print(mean_)
print(median_)
print(std_)

3.758666666666666
4.35
1.7585291834055212


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [23]:
p_l = iris_2d[:, 2]
s_l = iris_2d[:, 0]

volume = (np.pi * p_l * (s_l ** 2)) / 3

iris_2d = np.column_stack([iris_2d, volume])

iris_2d

array([[5.10000000e+00, 3.50000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.81326516e+01],
       [4.90000000e+00, 3.00000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.52004985e+01],
       [4.70000000e+00, 3.20000000e+00, 1.30000000e+00, 2.00000000e-01,
        3.00723721e+01],
       [4.60000000e+00, 3.10000000e+00, 1.50000000e+00, 2.00000000e-01,
        3.32380503e+01],
       [5.00000000e+00, 3.60000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.66519143e+01],
       [5.40000000e+00, 3.90000000e+00, 1.70000000e+00, 4.00000000e-01,
        5.19116770e+01],
       [4.60000000e+00, 3.40000000e+00, 1.40000000e+00, 3.00000000e-01,
        3.10221803e+01],
       [5.00000000e+00, 3.40000000e+00, 1.50000000e+00, 2.00000000e-01,
        3.92699082e+01],
       [4.40000000e+00, 2.90000000e+00, 1.40000000e+00, 2.00000000e-01,
        2.83832424e+01],
       [4.90000000e+00, 3.10000000e+00, 1.50000000e+00, 1.00000000e-01,
        3.77148198e+01],
       [5.40000000e+00, 3.7000

Run the following loaad command and solve the following questions

In [24]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Find the count of unique species.

In [28]:
unique_, count = np.unique(iris[:, -1], return_counts=True)
count

array([50, 50, 50])

Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is: Less than 3 –> ‘small’ 3-5 –> ‘medium’ ‘>=5 –> ‘large’

In [29]:
petal_length = iris_2d[:, 2]

bin_edges = [0, 3, 5, np.inf]

bin_labels = ['small', 'medium', 'large']

petal_length_bin = np.digitize(petal_length, bins=bin_edges, right=True)

petal_length_labels = np.array(bin_labels)[petal_length_bin - 1]

Find the most frequent value of petal length (3rd column) in iris dataset

In [33]:
unique_pl, count_pl = np.unique(iris[:, 2], return_counts=True)
mode_index = np.argmax(count_pl)
mode_pl = unique_pl[mode_index]
print(mode_pl)

b'1.5'
