In [5]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [6]:
a = np.ones(4, dtype = np.int64)
print(a)
# x = np.arange(4, dtype=np.int64)
# print(x)

[1 1 1 1]


Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [7]:
X = np.array([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [8]:
x = np.linspace(3.,10.,50)
print(x)

[ 3.          3.14285714  3.28571429  3.42857143  3.57142857  3.71428571
  3.85714286  4.          4.14285714  4.28571429  4.42857143  4.57142857
  4.71428571  4.85714286  5.          5.14285714  5.28571429  5.42857143
  5.57142857  5.71428571  5.85714286  6.          6.14285714  6.28571429
  6.42857143  6.57142857  6.71428571  6.85714286  7.          7.14285714
  7.28571429  7.42857143  7.57142857  7.71428571  7.85714286  8.
  8.14285714  8.28571429  8.42857143  8.57142857  8.71428571  8.85714286
  9.          9.14285714  9.28571429  9.42857143  9.57142857  9.71428571
  9.85714286 10.        ]


Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [9]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x = x.T
x = x.ravel()
print(x)

[1 4 2 5 3 6]


Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [10]:
x = np.array([1, 2, 3,4,5,6,7,8,9])
print(x[0:4],x[4:6],x[6:9])

[1 2 3 4] [5 6] [7 8 9]


Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [11]:
x = np.array([[1,2],[3,4]])
y = (x[0][0]+x[1][1])
z = (x[0][1]+x[1][0])
print(y+z)

10


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [12]:
x = np.array([[1,4],[3,1]])
print(np.sort(x, axis=0))
print(np.sort(x))


[[1 1]
 [3 4]]
[[1 4]
 [1 3]]


Q8 Get the indices that would sort x(as above) along the second axis.

Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [13]:
x = np.random.randint(0,10,(2,5))
print(x)
print(x.max(axis = 1))
print(np.argmax(x, axis=1))

[[2 6 2 1 9]
 [9 0 2 9 2]]
[9 9]
[4 0]


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [ ]:
import pandas as pd
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d)

Drop rows that contain a missing value.

In [15]:
iris = pd.DataFrame(iris_2d)
new_iris = iris.dropna()

Find the correlation between first two columns.

In [16]:
# new_iris[0].corr(new_iris[1])
corr = new_iris.corr()
print(corr[0:2][0:2])

          0         1         2         3
0  1.000000 -0.109369  0.871754  0.817954
1 -0.109369  1.000000 -0.420516 -0.356544


Find the mean,median and standard deviation of column 3.

In [17]:
# new_iris.describe()
new_iris.mean()


0    5.843333
1    3.054000
2    3.758667
3    1.198667
dtype: float64

Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [18]:
# volume = np.array((np.pi*'1'*'2'*'3')/3)

Run the following loaad command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris)

Find the count of unique species.

In [28]:
df = pd.DataFrame(iris)
print(df.info())

df[4].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       150 non-null    object
 1   1       150 non-null    object
 2   2       150 non-null    object
 3   3       150 non-null    object
 4   4       150 non-null    object
dtypes: object(5)
memory usage: 6.0+ KB
None


b'Iris-setosa'        50
b'Iris-versicolor'    50
b'Iris-virginica'     50
Name: 4, dtype: int64

Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is: Less than 3 –> ‘small’ 3-5 –> ‘medium’ ‘>=5 –> ‘large’

In [48]:
pl = np.array(df[2])
new_pl = pl.astype(float)

# print(new_pl)
arr = []
for x in new_pl:
  if(x<3):
    arr.append(f'{x}: Small')
  elif(x>3 and x<5):
    arr.append(f'{x}: medium')
  else:
    arr.append(f'{x}: large')
# print(arr)
ps = np.array(arr)
print(ps)

['1.4: Small' '1.4: Small' '1.3: Small' '1.5: Small' '1.4: Small'
 '1.7: Small' '1.4: Small' '1.5: Small' '1.4: Small' '1.5: Small'
 '1.5: Small' '1.6: Small' '1.4: Small' '1.1: Small' '1.2: Small'
 '1.5: Small' '1.3: Small' '1.4: Small' '1.7: Small' '1.5: Small'
 '1.7: Small' '1.5: Small' '1.0: Small' '1.7: Small' '1.9: Small'
 '1.6: Small' '1.6: Small' '1.5: Small' '1.4: Small' '1.6: Small'
 '1.6: Small' '1.5: Small' '1.5: Small' '1.4: Small' '1.5: Small'
 '1.2: Small' '1.3: Small' '1.5: Small' '1.3: Small' '1.5: Small'
 '1.3: Small' '1.3: Small' '1.3: Small' '1.6: Small' '1.9: Small'
 '1.4: Small' '1.6: Small' '1.4: Small' '1.5: Small' '1.4: Small'
 '4.7: medium' '4.5: medium' '4.9: medium' '4.0: medium' '4.6: medium'
 '4.5: medium' '4.7: medium' '3.3: medium' '4.6: medium' '3.9: medium'
 '3.5: medium' '4.2: medium' '4.0: medium' '4.7: medium' '3.6: medium'
 '4.4: medium' '4.5: medium' '4.1: medium' '4.5: medium' '3.9: medium'
 '4.8: medium' '4.0: medium' '4.9: medium' '4.7: medium'

Find the most frequent value of petal length (3rd column) in iris dataset

In [54]:
pl_df = pd.DataFrame(new_pl)
pl_df.mode()

0
0  1.5