In [2]:
import numpy as np
import pandas as pd

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [3]:
y=np.ones((np.arange(4,dtype=np.int64)).shape,dtype=np.int64)
y

array([1, 1, 1, 1], dtype=int64)

Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [4]:
x=np.array([[1,2],[3,4]])
x.reshape((2,2))

array([[1, 2],
       [3, 4]])

Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [5]:
x=np.random.uniform(3,10,(50))
x

array([9.02448087, 3.74187697, 7.24307003, 9.73611353, 4.99332606,
       9.598105  , 5.67714551, 9.48572383, 4.68576793, 5.49679778,
       4.61840149, 3.62248446, 9.54024249, 6.21024886, 6.0636115 ,
       9.72159336, 9.54744422, 5.87573116, 6.59361913, 6.13867694,
       7.6557912 , 9.94829556, 7.80537144, 5.21491285, 3.06840804,
       7.55744497, 9.04943568, 8.61225187, 9.63090196, 6.17584381,
       3.5971217 , 5.79416353, 4.93992036, 9.38607765, 4.86902819,
       8.54475791, 6.79762178, 8.74706023, 7.71675993, 7.08462207,
       8.80049208, 9.90345724, 9.50774414, 8.7797886 , 8.62909162,
       9.11705893, 8.30820713, 8.85283827, 4.16136074, 6.78497897])

Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [6]:
x=np.array([[1,2,3],[4,5,6]])
x.ravel()

array([1, 2, 3, 4, 5, 6])

Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [7]:
x=np.arange(1,10)
x1=x[0:4]
x2=x[4:6]
x3=x[6:9]
x1,x2,x3

(array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9]))

Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [8]:
x=np.array([[1,2],[3,4]])

#Inverse-
inv=np.linalg.inv(x)
print("Inverse-")
print(inv)

#Primary Diagonal Sum-
sum=np.trace(x)
print("The primary diagonal sum is",sum)

Inverse-
[[-2.   1. ]
 [ 1.5 -0.5]]
The primary diagonal sum is 5


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [9]:
x=np.array([[1,4],[3,1]])
x[1:].sort()
x

array([[1, 4],
       [1, 3]])

Q8 Get the indices that would sort x(as above) along the second axis.

In [10]:
x=np.array([[1,4],[3,1]])
np.argsort(x,axis=1)

array([[0, 1],
       [1, 0]], dtype=int64)

Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [11]:
x=np.random.uniform(0,10,(2,5))
max2=x[1:].max()
min2=x[1:].min()
indmax=x[1:].argmax()
indmin=x[1:].argmin()
print(x)
print("Maximum value:",max2)
print("Index of maximum value:",indmax)
print("Minimum value:",min2)
print("Index of minimum value:",indmin)

[[5.00342836 4.12173291 9.73739701 2.59945458 4.56894217]
 [2.61517981 7.5268026  3.58673476 0.70787542 3.352706  ]]
Maximum value: 7.526802598688521
Index of maximum value: 1
Minimum value: 0.7078754227998219
Index of minimum value: 3


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [12]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Drop rows that contain a missing value.

In [13]:
df=pd.DataFrame(iris_2d)
df.dropna(how='any')
iris_2d_new=np.array(df)
iris_2d_new

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Find the correlation between first two columns.

In [14]:
df=pd.DataFrame(iris_2d)
corr=df[0].corr(df[1])
corr

-0.10936924995064937

Find the mean,median and standard deviation of column 3.

In [15]:
mean=np.mean(iris_2d[:,3])
med=np.median(iris_2d[:,3])
std=np.std(iris_2d[:,3])
print("Mean=",mean)
print("Median=",med)
print("Standard Deviation=",std)

Mean= 1.1986666666666668
Median= 1.3
Standard Deviation= 0.7606126185881716


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [16]:
pi=np.pi
df[4]=(pi*df[2]*(df[0]**2))/3
df

0    1    2    3           4
0    5.1  3.5  1.4  0.2   38.132652
1    4.9  3.0  1.4  0.2   35.200498
2    4.7  3.2  1.3  0.2   30.072372
3    4.6  3.1  1.5  0.2   33.238050
4    5.0  3.6  1.4  0.2   36.651914
..   ...  ...  ...  ...         ...
145  6.7  3.0  5.2  2.3  244.445230
146  6.3  2.5  5.0  1.9  207.816354
147  6.5  3.0  5.2  2.0  230.069302
148  6.2  3.4  5.4  2.3  217.373079
149  5.9  3.0  5.1  1.8  185.910028

[150 rows x 5 columns]

Run the following loaad command and solve the following questions

In [36]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Find the count of unique species.

In [37]:
df=pd.DataFrame(iris,columns=names)
c=len(df.drop_duplicates())
print("The number of unique species is",c)

The number of unique species is 147


Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is: Less than 3 –> ‘small’ 3-5 –> ‘medium’ ‘>=5 –> ‘large’

In [38]:
df=pd.DataFrame(iris,columns=names)
df['petal_length_category']='large'
df['petallength']=pd.to_numeric(df['petallength'],errors='coerce')
df.loc[df['petallength']<3,'petal_length_category']='small'
df.loc[(df['petallength']>=3)&(df['petallength']<5),'petal_length_category']='medium'
print(df)

    sepallength sepalwidth  petallength petalwidth            species  \
0        b'5.1'     b'3.5'          1.4     b'0.2'     b'Iris-setosa'   
1        b'4.9'     b'3.0'          1.4     b'0.2'     b'Iris-setosa'   
2        b'4.7'     b'3.2'          1.3     b'0.2'     b'Iris-setosa'   
3        b'4.6'     b'3.1'          1.5     b'0.2'     b'Iris-setosa'   
4        b'5.0'     b'3.6'          1.4     b'0.2'     b'Iris-setosa'   
..          ...        ...          ...        ...                ...   
145      b'6.7'     b'3.0'          5.2     b'2.3'  b'Iris-virginica'   
146      b'6.3'     b'2.5'          5.0     b'1.9'  b'Iris-virginica'   
147      b'6.5'     b'3.0'          5.2     b'2.0'  b'Iris-virginica'   
148      b'6.2'     b'3.4'          5.4     b'2.3'  b'Iris-virginica'   
149      b'5.9'     b'3.0'          5.1     b'1.8'  b'Iris-virginica'   

    petal_length_category  
0                   small  
1                   small  
2                   small  
3          

Find the most frequent value of petal length (3rd column) in iris dataset

In [39]:
df=pd.DataFrame(iris)
d={}
c=0
for i in df[2]:
    if i not in d:
        d[i]=c+1
    else:
        d[i]+=1
lv=list(d.values())
ind=lv.index(max(lv))
lk=list(d.keys())
mfv=lk[ind]
print("The most frequent value of petal length is",mfv)



The most frequent value of petal length is b'1.5'
