In [1]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [2]:

y=np.array([[1,1,1,1]],dtype=np.int64)
y

array([[1, 1, 1, 1]])

Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [3]:
X = np.array([[1, 2], [3, 4]])
matrix = np.matrix(X)
matrix

matrix([[1, 2],
        [3, 4]])

Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [4]:
X=np.linspace(3,10,50)
X

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [5]:
x=np.array([[1, 2, 3], [4, 5, 6]])
array=x.T.ravel()
array

array([1, 4, 2, 5, 3, 6])

Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [9]:
x=np.array([1,2,3,4,5,6,7,8,9])
a1,a2,a3=np.split(x,[4,6])
print(a1)
print(a2)
print(a3)

[1 2 3 4]
[5 6]
[7 8 9]


Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [10]:
x=np.array([[1,2],[3,4]])
x_inv = np.linalg.inv(x)

Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [11]:
l=np.sort(x,axis=1)

Q8 Get the indices that would sort x(as above) along the second axis.

In [12]:
l_indices=x.argsort(axis=1)

Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [13]:
x=np.array([[1,2,3,4,5],[3,4,6,7,2]])
max_axis1=x.max(axis=1)
max_indices_axis1=x.argmax(axis=1)
min_axis1=x.min(axis=1)
min_indices_axis1=x.argmin(axis=1)

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [28]:
import numpy as np
import requests

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

# Fetching the data using requests
response = requests.get(url)

# Checking if the request was successful
if response.status_code == 200:
    # Decoding the content to text and splitting into lines
    data_text = response.content.decode('utf-8')
    lines = data_text.splitlines()

    # Loading the data using genfromtxt
    iris_2d = np.genfromtxt(lines, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])
    print("Data loaded successfully.")
else:
    print("Failed to fetch data from the URL.")


Data loaded successfully.


Drop rows that contain a missing value.

In [31]:
iris_2d_cleaned = iris_2d[~np.isnan(iris_2d).any(axis=1)]
iris_2d_cleaned

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Find the correlation between first two columns.

In [32]:
correlation = np.corrcoef(iris_2d[:, 0], iris_2d[:, 1])[0, 1]
correlation

-0.1093692499506493

Find the mean,median and standard deviation of column 3.

In [33]:
column_3 = iris_2d[:, 2]
mean_column_3 = np.mean(column_3)
median_column_3 = np.median(column_3)
std_column_3 = np.std(column_3)

Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [34]:
volume=(np.pi)*(iris_2d[:,2]*(iris_2d[:,0])*(iris_2d[:,0]))/3
volume=volume.reshape((150,1))
#print(volume)
iris=np.hstack([iris_2d,volume])
np.set_printoptions(suppress=True)
print(iris)

[[  5.1          3.5          1.4          0.2         38.13265163]
 [  4.9          3.           1.4          0.2         35.20049849]
 [  4.7          3.2          1.3          0.2         30.07237208]
 [  4.6          3.1          1.5          0.2         33.23805027]
 [  5.           3.6          1.4          0.2         36.65191429]
 [  5.4          3.9          1.7          0.4         51.91167701]
 [  4.6          3.4          1.4          0.3         31.02218026]
 [  5.           3.4          1.5          0.2         39.26990817]
 [  4.4          2.9          1.4          0.2         28.38324243]
 [  4.9          3.1          1.5          0.1         37.71481981]
 [  5.4          3.7          1.5          0.2         45.80442089]
 [  4.8          3.4          1.6          0.2         38.60389053]
 [  4.8          3.           1.4          0.1         33.77840421]
 [  4.3          3.           1.1          0.1         21.29895099]
 [  5.8          4.           1.2          0.2  

Run the following loaad command and solve the following questions

In [35]:
import numpy as np
import requests

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

# Fetching the data using requests
response = requests.get(url)

# Checking if the request was successful
if response.status_code == 200:
    # Decoding the content to text and splitting into lines
    data_text = response.content.decode('utf-8')
    lines = data_text.splitlines()

    # Loading the data using genfromtxt and assigning column names
    iris = np.genfromtxt(lines, delimiter=',', dtype='object', names=('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'))
    print("Data loaded successfully.")
else:
    print("Failed to fetch data from the URL.")


Data loaded successfully.


Find the count of unique species.

In [36]:
unique_species = np.unique(iris['species'])
count_unique_species = len(unique_species)

print(f"There are {count_unique_species} unique species in the dataset.")
print("Unique species:", unique_species)

There are 3 unique species in the dataset.
Unique species: [b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']


Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is: Less than 3 –> ‘small’ 3-5 –> ‘medium’ ‘>=5 –> ‘large’

In [37]:
# Extract the petal length column
petal_length = iris_2d[:, 2]

# Define bin edges
bin_edges = [0, 3, 5, np.inf]

# Define bin labels
bin_labels = ['small', 'medium', 'large']

# Bin the petal length column
bin_indices = np.digitize(petal_length, bins=bin_edges, right=True)

# Create a text array based on bin indices
text_array = np.array(bin_labels)[bin_indices - 1]

# Display the result
print(text_array)

['small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'large' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'small' 'medium' 'large'
 'large' 'large' 'large' 'large' 'large' 'medium' 'large' 'large' 'large'
 'large' 'large' 'large' 'medium' 'large' 'large' 'large' 

Find the most frequent value of petal length (3rd column) in iris dataset

In [38]:
petal_lengths = iris_2d[:, 2]  # Assuming petal length is in the third column

# Find unique values and their counts
unique_values, counts = np.unique(petal_lengths, return_counts=True)

# Find the most frequent petal length
most_frequent_value = unique_values[np.argmax(counts)]

# Display the result
print(f"The most frequent petal length is: {most_frequent_value}")

The most frequent petal length is: 1.5
