In [1]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [2]:
Y=np.ones((np.arange(4,dtype=np.int64)).shape,dtype=np.int64)
Y

array([1, 1, 1, 1], dtype=int64)

Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [3]:
X = np.array([[1, 2], [3, 4]])
X.reshape(2,2)

array([[1, 2],
       [3, 4]])

Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [4]:
Z=np.random.uniform(3,10,(50))
Z

array([3.86779257, 8.24626893, 9.28040494, 8.10238285, 6.67654863,
       8.80222106, 5.64026661, 9.06752962, 6.46010858, 9.5462299 ,
       6.19530987, 9.23692779, 4.96749009, 7.40779282, 5.94568703,
       4.07741794, 5.41950129, 9.62869191, 8.78526829, 7.9450798 ,
       3.31513213, 8.19495691, 5.59880057, 5.19175842, 6.36528533,
       4.04510727, 5.38364193, 6.58956163, 5.6373314 , 8.75895485,
       8.05281829, 6.10925759, 9.02401158, 4.53150933, 6.28910983,
       9.40781903, 9.29417007, 6.55182246, 5.01241684, 4.04300577,
       6.0585501 , 4.00491752, 8.2153756 , 7.51882862, 4.56612355,
       4.77940587, 8.70582047, 7.58835532, 3.82079248, 9.07887552])

Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [5]:
x=np.array([[1,2,3],[4,5,6]])
y=x.ravel(order='F')
print(y)

[1 4 2 5 3 6]


Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [6]:
X=np.array([1,2,3,4,5,6,7,8,9])
Y1,Y2,Y3=np.split(X,[4,6])
print(Y1)
print(Y2)
print(Y3)

[1 2 3 4]
[5 6]
[7 8 9]


Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [7]:
X=[[1,2],[3,4]]
inv_mat=np.linalg.inv(X)
print(inv_mat)
s=np.trace(X)
print(s)

[[-2.   1. ]
 [ 1.5 -0.5]]
5


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [8]:
x=[[[1,4],[3,1]]]
sort_x=np.sort(x,axis=1)
print(sort_x)

[[[1 1]
  [3 4]]]


Q8 Get the indices that would sort x(as above) along the second axis.

In [9]:
x = ([[1, 4],[3, 1]])

sort_idx = np.argsort(x, axis=1)

print(sort_idx)

[[0 1]
 [1 0]]


Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [10]:
X=np.random.randint(1,10,(2,5))
print(X)
print(np.min(X,axis=1))
print(np.max(X,axis=1))

[[9 7 5 9 6]
 [1 1 3 3 9]]
[5 1]
[9 9]


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [11]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Drop rows that contain a missing value.

In [12]:

iris_2d=iris_2d[~np.isnan(iris_2d).any(axis=1)]

Find the correlation between first two columns.

In [13]:
print(np.corrcoef(iris_2d[:,0],iris_2d[:,1])[0,1])

-0.1093692499506493


Find the mean,median and standard deviation of column 3.

In [14]:
print(np.mean(iris_2d[:,2]))
print(np.median(iris_2d[:,2]))
print(np.std(iris_2d[:,2]))

3.758666666666666
4.35
1.7585291834055212


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [15]:
volume=(np.pi)*(iris_2d[:,2]*(iris_2d[:,0])*(iris_2d[:,0]))/3
volume=volume.reshape((150,1))
#print(volume)
iris=np.hstack([iris_2d,volume])
np.set_printoptions(suppress=True)
print(iris)

[[  5.1          3.5          1.4          0.2         38.13265163]
 [  4.9          3.           1.4          0.2         35.20049849]
 [  4.7          3.2          1.3          0.2         30.07237208]
 [  4.6          3.1          1.5          0.2         33.23805027]
 [  5.           3.6          1.4          0.2         36.65191429]
 [  5.4          3.9          1.7          0.4         51.91167701]
 [  4.6          3.4          1.4          0.3         31.02218026]
 [  5.           3.4          1.5          0.2         39.26990817]
 [  4.4          2.9          1.4          0.2         28.38324243]
 [  4.9          3.1          1.5          0.1         37.71481981]
 [  5.4          3.7          1.5          0.2         45.80442089]
 [  4.8          3.4          1.6          0.2         38.60389053]
 [  4.8          3.           1.4          0.1         33.77840421]
 [  4.3          3.           1.1          0.1         21.29895099]
 [  5.8          4.           1.2          0.2  

Run the following loaad command and solve the following questions

In [16]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Find the count of unique species.

In [17]:
unique_species,counts=np.unique(iris[:,-1],return_counts=True)
print(counts)

[50 50 50]


Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is: Less than 3 –> ‘small’ 3-5 –> ‘medium’ ‘>=5 –> ‘large’

In [19]:
# Find the petal length column
petal_length = iris_2d[:, 2]

# Define bin edges
bin_edges = [0, 3, 5, np.inf]

# Define bin labels
bin_labels = ['small', 'medium', 'large']

# Bin the petal length column
bin_indices = np.digitize(petal_length, bins=bin_edges, right=True)

# Array created based on bin indices
text_array = np.array(bin_labels)[bin_indices - 1]

print(text_array)

['small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'large' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'small' 'medium' 'large'
 'large' 'large' 'large' 'large' 'large' 'medium' 'large' 'large' 'large'
 'large' 'large' 'large' 'medium' 'large' 'large' 'large' 

Find the most frequent value of petal length (3rd column) in iris dataset

In [20]:
petal_lengths = iris_2d[:, 2]  # Assuming petal length is in the third column

unique_values, counts = np.unique(petal_lengths, return_counts=True)

most_frequent_value = unique_values[np.argmax(counts)]

print(f"The most frequent petal length is: {most_frequent_value}")

The most frequent petal length is: 1.5
