In [2]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
 x = np.arange(4, dtype=np.int64)
ar = np.ones_like(x)
print(ar)

Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [ ]:
 X = np.array([[1, 2], [3, 4]])
 m=np.matrix(X)
 print(m)

Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [10]:
arr= np.linspace(3., 10., 50)
print(arr)

[ 3.          3.14285714  3.28571429  3.42857143  3.57142857  3.71428571
  3.85714286  4.          4.14285714  4.28571429  4.42857143  4.57142857
  4.71428571  4.85714286  5.          5.14285714  5.28571429  5.42857143
  5.57142857  5.71428571  5.85714286  6.          6.14285714  6.28571429
  6.42857143  6.57142857  6.71428571  6.85714286  7.          7.14285714
  7.28571429  7.42857143  7.57142857  7.71428571  7.85714286  8.
  8.14285714  8.28571429  8.42857143  8.57142857  8.71428571  8.85714286
  9.          9.14285714  9.28571429  9.42857143  9.57142857  9.71428571
  9.85714286 10.        ]


Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [14]:
x1 = np.array([[1, 2, 3], [4, 5, 6]])
y= x1.T.reshape(-1)
print(y)

[1 4 2 5 3 6]


Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [15]:
x2 = np.arange(1, 10)
s=np.split(x2, [4, 6])
print(s)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [53]:
x4=[[1,2],[3,4]]
inv=np.linalg.inv(x4)
print(inv)
s=np.trace(x4)
print(s)

[[-2.   1. ]
 [ 1.5 -0.5]]
5


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [25]:
x3 =[[1, 4], [3, 1]]
sorted_x = np.sort(x3, axis=1)
print(sorted_x)


[[1 4]
 [1 3]]


Q8 Get the indices that would sort x(as above) along the second axis.

In [27]:
ind= np.argsort(x3, axis=1)
print(ind)

[[0 1]
 [1 0]]


Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [35]:
x=np.random.randint(1,10,(2,5))
print(x)
mav= np.amax(x, axis=1)
mai= np.argmax(x, axis=1)
print("max value",mv,"indices",mi)
miv= np.amin(x, axis=1)
mii= np.argmin(x, axis=1)
print("min value",miv,"indices",mii)

[[9 8 8 6 2]
 [5 8 1 2 7]]
max value [9 8] indices [2 2]
min value [2 1] indices [4 2]


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [36]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Drop rows that contain a missing value.

In [ ]:
iris_2d=iris_2d[~np.isnan(iris_2d).any(axis=1)]
print(iris_2d)

Find the correlation between first two columns.

In [42]:
print(np.corrcoef(iris_2d[:,0],iris_2d[:,1])[0,1])


-0.10936924995064937


Find the mean,median and standard deviation of column 3.

In [43]:
print(np.mean(iris_2d[:,2]))
print(np.median(iris_2d[:,2]))
print(np.std(iris_2d[:,2]))

3.758666666666666
4.35
1.7585291834055212


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [ ]:
volume=(np.pi)*(iris_2d[:,2]*(iris_2d[:,0])*(iris_2d[:,0]))/3
iris = np.column_stack((iris_2d, volume.reshape(150,1)))
np.set_printoptions(suppress=True)
print(iris)

Run the following loaad command and solve the following questions

In [47]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Find the count of unique species.

In [48]:
unique_species,counts=np.unique(iris[:,-1],return_counts=True)
print(counts)

[50 50 50]


Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is: Less than 3 –> ‘small’ 3-5 –> ‘medium’ ‘>=5 –> ‘large’

In [ ]:
petal_length = iris_2d[:, 2]
bin_edges = [0, 3, 5, np.inf]
bin_labels = ['small', 'medium', 'large']
bin_indices = np.digitize(petal_length, bins=bin_edges, right=True)
text_array = np.array(bin_labels)[bin_indices - 1]
print(text_array)

Find the most frequent value of petal length (3rd column) in iris dataset

In [51]:
petal_lengths = iris_2d[:, 2]
unique_values, counts = np.unique(petal_lengths, return_counts=True)
most_frequent_value = unique_values[np.argmax(counts)]
print(f"The most frequent petal length is: {most_frequent_value}")

The most frequent petal length is: 1.5
